### ISSUE TITLE
question/problem about the training and the evaluation results

### ISSUE THREAD

**Issue by DarlineFiedler** [nlpyang/BertSum#103]
I have no idea if the training and the evaluation are going to be done correctly. And how can I look at the values of the evaluation. Below I have listed the results I get and which data is generated. I hope someone can help me. 

When I start the training it runs through without any errors, but I don't know if the console output is correct.  I get this as last output: 
![image](https://user-images.githubusercontent.com/33732630/89129765-40142600-d500-11ea-815f-a9004462848c.png)

when I run the time: 
`!python automatische-generierung-von-titeln-und-abstracts/BertSum/src/train.py -mode train -encoder transformer -dropout 0.1 -bert_data_path bert_data/test/test -model_path automatische-generierung-von-titeln-und-abstracts/BertSum/models/test -lr 2e-3 -visible_gpus 0  -gpu_ranks 0 -world_size 1 -report_every 50 -save_checkpoint_steps 1000 -batch_size 3000 -decay_method noam -train_steps 000 -accum_count 2 -log_file automatische-generierung-von-titeln-und-abstracts/BertSum/logs/bert_transformer -use_interval true -warmup_steps 10000 -ff_size 2048 -inter_layers 2 -heads 8`
and how many steps is the right number? 

When I start the evaluation with the saved data I get this as last output: 
![image](https://user-images.githubusercontent.com/33732630/89130070-61761180-d502-11ea-9cf0-c23fcef34f17.png)

I run this: 
`!python automatische-generierung-von-titeln-und-abstracts/BertSum/src/train.py  -mode validate -bert_data_path bert_data/test/test -model_path automatische-generierung-von-titeln-und-abstracts/BertSum/models/test -visible_gpus 0  -gpu_ranks 0 -batch_size 30000  -log_file automatische-generierung-von-titeln-und-abstracts/BertSum/logs/bert_transformer_vali -result_path automatische-generierung-von-titeln-und-abstracts/BertSum/results/test -bert_config_path automatische-generierung-von-titeln-und-abstracts/BertSum/bert_config_uncased_base.json -test_all -block_trigram true`

But my results/test folder is simply empty. But there are some data in results. This one:  
![image](https://user-images.githubusercontent.com/33732630/89130116-aef27e80-d502-11ea-891b-3e72f657b1a2.png)

**Comment by DarlineFiedler** [comment]
And I have a second Question.

How can I generate and display specific example outputs? So that I give a text as input and the model then gives me the generated counterpart?

**Comment by Dejavu2019** [comment]
I donot know how to train the dates, could you help me? thank U very much!
