### ISSUE TITLE
Is there a list of stop words?

### ISSUE THREAD

**Issue by DarlineFiedler** [nlpyang/BertSum#106]
Is there a list of stop words in Rouge?

How can I display the n-grams of rouge? I need it for my thesis.
and does anyone know how to use a different evaluation?

**Comment by DarlineFiedler** [comment]
I have another question
Is there a list of stop words?

**Comment by tschomacker** [comment]
You could use https://github.com/kavgan/ROUGE-2.0 for inlcuding a stop word list. There are a few stop word lists: http://www.lextek.com/manuals/onix/stopwords2.html (english), https://tcpip.wtf/en/deutsche-stopwords.htm (german). I think the most easy evaluation metric to use would be BLEU

**Comment by DarlineFiedler** [comment]
that means das ROUGE 1.5.5 don't have a stop word list?

**Comment by tschomacker** [comment]
there is a `-s` argument for using a stop word list but I could not find where the stop word list in the repository: https://github.com/andersjo/pyrouge/tree/master/tools/ROUGE-1.5.5

**Comment by DarlineFiedler** [comment]
Thanks
