### ISSUE TITLE
A question about the final vocabulary

### ISSUE THREAD

**Issue by jiahuanluo** [nlpyang/BertSum#11]
Dear,
Thanks for your great jobs. 
I have a question about the final vocabulary.

Should I maintain a **vocabulary for the corpus**, or use the exact vocabulary privided by the `BertTokenizer.from_pretrained('bert-base-uncased').vocab` ? 
In other words, should I use the exact vocab in BerTokensizer when finetuning Bert?
I found that there are only **27615** English words in the vocab of BertTokenizer.

Best regards.

**Comment by nlpyang** [comment]
Hi,
No external vocabulary is used.
You should use BERT vocabulary, and it is a subtoken vocabulary, so 27615 is enough.
Please refer to original BERT paper for details.

**Comment by jiahuanluo** [comment]
Dear,
Thanks for your reply.

Maybe this is a stupid question. But I haven't figured it out yet.

**How can I generate the original word in the summary?** 

Since BERT vocabulary is a subtoken vocabulary, is there another function for mapping the subtoken to the original vocabulary?
Sorry about the question. Maybe I am getting to a dead end on this question.
Any help would be appreciated.

Best regards.

**Comment by nlpyang** [comment]
1. The process to sub-tokenize a text is invertible
2. For extractive summarization, we only predict the indexes of selected sentences, then we select raw sentence with these indexes.
