### ISSUE TITLE
How to continue training from previous checkpoints?

### ISSUE THREAD

**Issue by namln2k** [nlpyang/BertSum#118]
Hi guys I'm new to nlp and summarization in particular. I'm running the BERT+RNN model on Google Colab. I understand that the param "-save_checkpoint_steps 1000" in the training script helps save the model every 1000 train steps. However I don't know how to continue from that checkpoint (All I know is to run the training script: "python train.py ....." and each time, it starts from the very beginning). In detail, I have mounted my google drive to the notebook and the checkpoints are saved as in the below image. Can someone tell me how to do that please (Is there a param I should add to the script to make it work?). Many thanks in advance! 
![image](https://user-images.githubusercontent.com/82750234/145804726-54ffa823-525a-4382-8567-4259be6ea703.png)
![image](https://user-images.githubusercontent.com/82750234/145804837-56f12888-bed1-428f-a01d-c544fff20a90.png)

**Comment by Anothernewcomer** [comment]
use the paramater args.train_from

**Comment by namln2k** [comment]
> use the paramater args.train_from

Yeah I just found out this afternoon :v Thanks anw!
![image](https://user-images.githubusercontent.com/82750234/145844070-ec9d1c06-b721-4160-bb9c-eac68d84855a.png)

**Comment by Anothernewcomer** [comment]
> > use the paramater args.train_from
> 
> Yeah I just found out this afternoon :v Thanks anw! ![image](https://user-images.githubusercontent.com/82750234/145844070-ec9d1c06-b721-4160-bb9c-eac68d84855a.png)

 I want to use this model but I'm new to this and not sure about whether my loss trend is correct, can we talk?

**Comment by namln2k** [comment]
> > > use the paramater args.train_from
> > 
> > 
> > Yeah I just found out this afternoon :v Thanks anw! ![image](https://user-images.githubusercontent.com/82750234/145844070-ec9d1c06-b721-4160-bb9c-eac68d84855a.png)
> 
> I want to use this model but I'm new to this and not sure about whether my loss trend is correct, can we talk?

I'm a newbie too, man. I'm just attempting to complete a short course at my school and I'm currently not so interested in this field.
