### ISSUE TITLE
Empty Logs Directory for First Run

### ISSUE THREAD

**Issue by zwol3027** [nlpyang/BertSum#12]
I am trying to mimic the code in Google Colab using a GPU, however, after preprocessing when I try run the BERT+Classifier model for the first time (with visible_gpus 0 etc.), I have an error that the '/logs/bert_classifier' file/directory doesn't exist as the logs folder is empty. Should there be anything there? Or is the issue that the code hasn't downloaded the bert model?

![BertSum logs error](https://user-images.githubusercontent.com/18254743/56200381-4c027d00-605c-11e9-91d5-16b2841f862e.PNG)

Thanks

**Comment by nlpyang** [comment]
……please debug and check the -log_path param.

you shoud cd into src and run the code.

**Comment by Santosh-Gupta** [comment]
@zwol3027 I am wondering if you could share your notebook. I am trying to run in colab as well
