### ISSUE TITLE
Why Stanford Core-NLP tokenizer instead of WordPiece?

### ISSUE THREAD

**Issue by alvin-leong** [nlpyang/BertSum#13]
May I ask why you use the Stanford Core-NLP tokenizer instead of the default BERT WordPiece tokenizer?

**Comment by nlpyang** [comment]
We do use BERT WordPiece, but it is applied on Core-NLP tokenized text.
Two reasons to use Core-NLP first:
1. We need sentence splitting
2. For a fair comparison with previous systems, since ROUGE will be different for different tokenizers.

**Comment by enzoampil** [comment]
Is it safe to assume that BERTSUM will perform without issues on input text tokenized using a tokenizer other than Core-NLP as long as we implement sentence splitting?
