### ISSUE TITLE
Experimenting with the number of sentences selected

### ISSUE THREAD

**Issue by Shashi456** [nlpyang/BertSum#17]
I read in the paper that for extractive summarization, you only take the top 3 sentence scores, There's no explicit mention of this in the code, is there any way i could modify this to get more sentences and experiment a little?

**Comment by nlpyang** [comment]
Hi, this is now hardcoded in the codes. If you want, you can change the line 282 in trainer.py by replacing 3 with the number you want.

`                                if ((not cal_oracle) and (not self.args.recall_eval) and len(_pred) == 3):
`

**Comment by Shashi456** [comment]
@nlpyang, I had a few more doubts, mind if I ask?

**Comment by nlpyang** [comment]
please ask

**Comment by Shashi456** [comment]
@nlpyang so, is there any way to load the training set in the test set way.
I was going through your code, and i found that when you are test mode you also load src and tgt text. 
The reason i want to do this, is to like display all 3 one after the other. The source text, the output by the model and the gold reference and maybe analyse them. 
The first thing i did was load the weights into the model, but when i tried to load the training set in the test format i ran into an error.
I tried doing something like this in jupyter:
``` 
test_iter =data_loader.Dataloader(args, load_dataset(args, 'train', shuffle=False),
                                  args.batch_size, device, shuffle=False, is_test=True)
```

I kept running into this error :
```
FileNotFoundError: [Errno 2] No such file or directory: '../data/bert_data/cnndm.train.pt'
```

this probably happens because the execution is going into the : 
```
# Only one inputters.*Dataset, simple!
     98         pt = args.bert_data_path + '.' + corpus_type + '.pt'
---> 99       yield _lazy_dataset_loader(pt, corpus_type)
```

Any idea how i could go about solving this problem?

Thank you so much for your help.

**Comment by nlpyang** [comment]
The error shows you are passing the run argument for -bert_data_path 
change it to '../bert_data'

**Comment by nlpyang** [comment]
The error shows you are passing the wrong argument for -bert_data_path
change it to '../bert_data'

**Comment by nlpyang** [comment]
The error shows you are passing the wrong argument for -bert_data_path
change it to '../bert_data/cnndm'

**Comment by Shashi456** [comment]
@nlpyang im sorry to ask but the gold summaries are gold standard or the oracle summaries?

**Comment by nlpyang** [comment]
they are gold standard

**Comment by Machine-Tom** [comment]
Excuse me. What do you mean by gold standard here?

**Comment by stylelohan** [comment]
> The error shows you are passing the wrong argument for -bert_data_path
> change it to '../bert_data/cnndm'

Sorry bothering. I came into the same question and I changed the argument command as you said, but it didn't work. Do you have any other solutions?

Thanks!

**Comment by nlpyang** [comment]
@Machine-Tom reference summaries, human-written highlights
