### ISSUE TITLE
How to test？

### ISSUE THREAD

**Issue by uHm1995** [nlpyang/BertSum#19]
Hello，can u tell me how to test？how to set the -test_from
can you show me the order?

**Comment by nlpyang** [comment]
python train.py -mode test -bert_data_path ../bert_data/cnndm -model_path MODEL_PATH  -visible_gpus 0  -gpu_ranks 0 -batch_size 30000  -log_file LOG_FILE  -result_path RESULT_PATH  -block_trigram true -test_from YOUR_SAVE_MODEL_FILE

**Comment by uHm1995** [comment]
Hi，
Why my program keep downloading data，when I train the classifier？
Thanks！
![_ ~$QA87YDN@1J4JSCG _D8](https://user-images.githubusercontent.com/37919100/57051341-a71aad80-6cb3-11e9-98e3-4f7e36607bfb.png)

**Comment by nlpyang** [comment]
please paste your commands

**Comment by uHm1995** [comment]
Hi,my commend is：
python train.py -mode train -encoder classifier -dropout 0.1 -bert_data_path ../bert_data/cnndm -model_path ../models/bert_classifier -lr 2e-3 -visible_gpus 1  -gpu_ranks 1 -world_size 1 -report_every 50 -save_checkpoint_steps 1000 -batch_size 3000 -decay_method noam -train_steps 50000 -accum_count 2 -log_file ../logs/bert_classifier -use_interval true -warmup_steps 10000

I just use one gpu，and data filename  is correct.

**Comment by nlpyang** [comment]
I can't figure out the mistake based on your description, the command seems correct, except gpu_ranks should be 0.

**Comment by uHm1995** [comment]
Thanks for your help~

**Comment by rakshithxaloori** [comment]
[https://colab.research.google.com/drive/1wC3qqaLqZpdp-vAKM7xs3C7ro4OUD5Ht?usp=sharing](url)

I'm using my own dataset.
**(i)**In the potential summary sentences, only the first few lines are considered when the test file contains more than the lines considered, **(the `selected_ids` array in the last cell's output)**.
Can someone please tell me what I'm doing wrong?

All I've changed is the hardcoded number of sentences in the trainer.test() function from `3` to a dynamic number, which I think shouldn't bother the selection of sentences.

In the output of the last cell in colab notebook, the `j` in the print statement is the **j** in the loop of trainer.test() function.

**(ii)** The last error of the last cell's output, I set the ROUGE paths correctly or have I not?

Any help is appreciated, thanks!
