### ISSUE TITLE
Access to pretrained model

### ISSUE THREAD

**Issue by BurakaKrishna** [nlpyang/BertSum#2]
Hi Yang , i wanted to see the pretrained model results,May you please provide access to the pretrained model,the permission to download is not open from the link mentioned in the README file

**Comment by nlpyang** [comment]
Hi, it should be OK now.

**Comment by nlpyang** [comment]
Sorry for removing the pre-trained model. We are formalizing the pre-print as a paper, the pre-trained model will be released after that.
