### ISSUE TITLE
Evaluation part

### ISSUE THREAD

**Issue by opababy** [nlpyang/BertSum#22]
![擷取](https://user-images.githubusercontent.com/29200930/57016230-9d5d5f80-6c4b-11e9-98f7-c1dc44270dc9.PNG)
Sorry, I encountered some errors while running the model evaluation.  How can I solve it?

**Comment by nlpyang** [comment]
this error is related to pyrouge but not bertsum, please see https://github.com/bheinzerling/pyrouge for a solution.
