### ISSUE TITLE
A question about format_to_lines 

### ISSUE THREAD

**Issue by Limtle** [nlpyang/BertSum#23]
HI,

My command 
 `python3 preprocess.py -mode tokenize -raw_path ../raw_stories/ -save_path ../merged_stories_tokenized -log_file ../logs/cnndmtoken.log -n_cpus 50  -log_file ../logs/cnndmtoken.log
`
` python3 preprocess.py -mode format_to_lines -raw_path ../merged_stories_tokenized -save_path ../json_data/cnndm -map_path ../urls -lower  -log_file ../logs/cnndmtoken.log`

But After format_to_lines tgt in my file is a empty list

a part of cnndm.train.0.json

> portedly", "treated", "for", "appendicitis", "but", "was", "well", "enough", "to", "walk", "out", "of", "the", "clinic", "on", "his", "own", "@highlight", "took", "a", "private", "jet", "to", "the", "argentinian", "capital", "and", "is", "now", "under", "`", "observation", "'"]], "tgt": []},

 Appreciated!

**Comment by nlpyang** [comment]
please paste your input to format_to_lines

**Comment by cool425589** [comment]
[https://jsoneditoronline.org/?id=deb973a27d7546e78f32f6d03783fc5a](url)

**Comment by nlpyang** [comment]
@cool425589 are you an alias of @Limtle ?
If so, with your provided json file and the command, I do get correct results.

**Comment by Limtle** [comment]
Yes. i already deleted the comments. Sorry for the confusion.
This my json.
> [https://jsoneditoronline.org/?id=deb973a27d7546e78f32f6d03783fc5a](url)

I find my token '@highlight' in .story did not be split to single sentence.

So flag in  prepro/data_builder.py/load_json will not be work? Any problem in my stanford-corenlp-3.8.0.jar setting? or any suggestion for me.

Appreciated!

**Comment by nlpyang** [comment]
Hi, there seems to be a bug in data_builder. This should be solved now. Could you pull the code to see if it is OK? 

I had to change the data_builder for preprocessing with new CoreNLP versions, and the commandline parameters seem to be different from previous versions. Sorry for the inconvenience.
