### ISSUE TITLE
ROUGE1.5.5

### ISSUE THREAD

**Issue by FTUfred** [nlpyang/BertSum#24]
hi,
Can i have your ROUGE1.5.5 file or download link?
Beacause my lead3 and other result is better than the result on your paper .
Is it normal ?

Thanks.

**Comment by nlpyang** [comment]
My rouge program should be no different from yours. The preprocessing codes have been modified, so if your result is not marginally different, it should be normal.

**Comment by FTUfred** [comment]
Sorry. 
I use pyrouge0.1.3  and this [ROUGE1.5.5](https://github.com/andersjo/pyrouge/tree/master/tools/ROUGE-1.5.5)
But my lead3 score different from result on paper. 
![image](https://user-images.githubusercontent.com/49365155/57191775-cc314980-6f5b-11e9-8c1a-65eaa1965396.png)

**Comment by nlpyang** [comment]
Rouge depends on tokenization, preprocessing and other factors. The difference between our scores is minor and acceptable.
