### ISSUE TITLE
Problem for artical

### ISSUE THREAD

**Issue by uHm1995** [nlpyang/BertSum#27]
Hi，sorry to trouble you:
:how can I get the original article?
For example, the reference summary ref.83.txt and can.83.txt, i cannot find the original article.

And the results I get are different from yours, my pyrouge configuration is correct, what's wrong with me? can you help me?        Thanks!
This is classifier log file
![YN$)7E1}OEILGG~(QA@ W38](https://user-images.githubusercontent.com/37919100/57581794-29df0c00-74ef-11e9-97e2-8f51c4ea95df.png)

![MI2 }@A05L0SLURD}%IQ4PF](https://user-images.githubusercontent.com/37919100/57581778-f7351380-74ee-11e9-9179-db4a5e8da8e0.png)
![KL3GUTWE9Y JX5DO`G_5KUN](https://user-images.githubusercontent.com/37919100/57581779-f7cdaa00-74ee-11e9-9c3c-15637f60b679.png)
![`HF 6~PE 0_(`FI78 R03YL](https://user-images.githubusercontent.com/37919100/57581780-f8664080-74ee-11e9-8dbc-7dece7db3c72.png)

**Comment by nlpyang** [comment]
I cannot help you with the information you provided. please always patse your commsnds.

**Comment by uHm1995** [comment]
problem1:
the commend for train classifier is:
python train.py -mode train -encoder classifier -dropout 0.1 -bert_data_path /home/test/WangHN/BertSum-master/bert_data/cnndm -model_path /home/test/WangHN/BertSum-master/models/bert_classifier -lr 2e-3 -visible_gpus 0,1,2 -gpu_ranks 0,1,2 -world_size 3 -report_every 50 -save_checkpoint_steps 1000 -batch_size 3000 -decay_method noam -train_steps 50000 -accum_count 2 -log_file /home/test/WangHN/BertSum-master/logs/bert_classifier -use_interval true -warmup_steps 10000
for test classifier is:
python train.py -mode validate -bert_data_path /home/test/WangHN/BertSum-master/bert_data/cnndm -model_path /home/test/WangHN/BertSum-master/models/bert_classifier -visible_gpus 1 -gpu_ranks 0 -batch_size 30000 -log_file /home/test/WangHN/BertSum-master/logs/Evaluation/bert_classifier -result_path /home/test/WangHN/BertSum-master/results/classifier/cnndm -test_all -block_trigram true

the log file's results are what I provide above , the rouge score is low,  this is also true in another （rnn and transformer）

problem2:
for the summary results, how can I find the original article ,for example ref.83.txt and can.83.txt's original article?

**Comment by nlpyang** [comment]
could you run -mode lead to see if the data is correct

**Comment by uHm1995** [comment]
how to do this

**Comment by nlpyang** [comment]
python train.py -mode lead -bert_data_path ../../../bertabs/bert_data/cnndm  -visible_gpus -1 -batch_size 30000  -log_file cnndm_lead  -result_path ../results/cnndm_lead -block_trigram false

**Comment by uHm1995** [comment]
![`(LX8}JT~U X8NY)Z7(S7$8](https://user-images.githubusercontent.com/37919100/57589925-8fb4ad80-755a-11e9-9316-efedcc93b231.png)
dont have the mode  lead

**Comment by nlpyang** [comment]
please checkout to dev branch and run lead

**Comment by uHm1995** [comment]
sorry，where is dev branch

**Comment by nlpyang** [comment]
please google for "check out branches on github"

**Comment by uHm1995** [comment]
![L`HVM$D0_(NN$7}V)H$}D2L](https://user-images.githubusercontent.com/37919100/57592456-5df71300-7569-11e9-850a-ff3480a6cc44.png)
I run mode -lead ，got this results， ~.~

**Comment by nlpyang** [comment]
apparently the data is wrong. how do you process the data?

**Comment by uHm1995** [comment]
I process the data by the commend you provide，
Put the CNN story file and the daily mail story file under one file，using the Stanford CoreNLP version:3.7.0
then got the sentence splitting and token, just follow the step 3,4,5 , then got the bert_data file.

**Comment by nlpyang** [comment]
please past some parts of the json file in got from format_to_lines

**Comment by nlpyang** [comment]
or could you rerun the preprocessing process and calculate lead
