### ISSUE TITLE
Where can I find the rouge scores from the evaluation script?

### ISSUE THREAD

**Issue by enzoampil** [nlpyang/BertSum#29]
The training and evaluation script I believe are showing me only "xent", cross entropy loss (I'm assuming). Where can I find the rogue scores that were published in your paper? Thanks.

**Comment by nlpyang** [comment]
evaluation will calculate rouges

**Comment by enzoampil** [comment]
Where can I find the rogue scores? The logs only contain "xent"

**Comment by nlpyang** [comment]
-mode validate and -test_all will load all checkpoints to calculate dev loss and select the best ones to produce summaries, which could take some time, and during this process, no summaries will be produced. Please read the codes for details.

**Comment by enzoampil** [comment]
got it thanks
