### ISSUE TITLE
Unable to preprocess my own data

### ISSUE THREAD

**Issue by HenriAW** [nlpyang/BertSum#3]
Hi, I'm currently trying to preprocess my own news articles so that I can use it with the pre-trained model. I'm currently trying to use Stanford NLP to preprocess the data and am then looking to use preprocess.py. Am I on the correct lines, and is this something I need to do if I want to generate summaries of my own articles?

**Comment by nlpyang** [comment]
Hi, I add a sample json file in the json_data directory. If you want to process your own data, just format it as the sample file and run the format_to_bert function.

**Comment by HenriAW** [comment]
Thanks Yang, I managed to get this working this morning! Thanks for adding the sample json file to the repository as well, that was very useful!

**Comment by Santosh-Gupta** [comment]
For preprocessing in format_to_lines mode, it asks for a MAP_PATH which is the directory containing the urls files (../urls)

A sample text of the urls files in here

https://raw.githubusercontent.com/nlpyang/BertSum/master/urls/mapping_test.txt

However, I am using new data which doesn't have a urls file. 

Did anyone find a workaround?
