### ISSUE TITLE
testing on new text

### ISSUE THREAD

**Issue by jorgeramirez** [nlpyang/BertSum#31]
Hi, 

I am currently in the process of testing some recent approaches for extractive summarization. I just want to test the models on a collection of text that I have, but I still could not sort out what should I do just to summarize a new piece of text using your codebase. Any pointers?

Thanks!

**Comment by nlpyang** [comment]
Hi,

Ther is a sample json file in the json_data directory. If you want to process your own data, just format it as the sample file and run the format_to_bert function.

**Comment by jorgeramirez** [comment]
Great, thanks!

**Comment by Santosh-Gupta** [comment]
What about the -map_path parameter? New data doesn't have a urls file.
