### ISSUE TITLE
Training without GPU

### ISSUE THREAD

**Issue by vnik18** [nlpyang/BertSum#33]
Hi, I have downloaded the processed data and I am trying to run the command 

`python train.py -mode train -encoder classifier -dropout 0.1 -bert_data_path ../bert_data/cnndm -model_path ../models/bert_classifier -lr 2e-3 -visible_gpus 0,1,2  -gpu_ranks 0,1,2 -world_size 3 -report_every 50 -save_checkpoint_steps 1000 -batch_size 3000 -decay_method noam -train_steps 50000 -accum_count 2 -log_file ../logs/bert_classifier -use_interval true -warmup_steps 10000`

However, I get the error:

`RuntimeError: the distributed NCCL backend is not available; try to recompile the THD package with CUDA and NCCL 2+ support at /Users/distiller/project/conda/conda-bld/pytorch_1556653464916/work/torch/lib/THD/process_group/General.cpp:20`

My machine does not have a GPU. Is there any way I can run this only on a CPU? Thanks!

**Comment by nlpyang** [comment]
Hi, if you want to use cpu, please set  -visible_gpus -1
But you should know this would be very slow.

**Comment by vnik18** [comment]
Thank you. I have set visible_gpus, gpu_ranks and world_size to be -1. I also reduced the number of train_steps, batch_size and warmup_steps just for experimentation purposes to see that everything is working well. So I am running the command:

python train.py -mode train -encoder classifier -dropout 0.1 -bert_data_path ../bert_data/cnndm -model_path ../models/bert_classifier -lr 2e-3 -visible_gpus -1  -gpu_ranks -1 -world_size -1 -report_every 10 -save_checkpoint_steps 1000 -batch_size 300 -decay_method noam -train_steps 500 -accum_count 2 -log_file ../logs/bert_classifier -use_interval true -warmup_steps 1000

I however get the error:

Traceback (most recent call last):
  File "train.py", line 340, in <module>
    train(args, device_id)
  File "train.py", line 272, in train
    trainer.train(train_iter_fct, args.train_steps)
  File "/Users/vvn/Desktop/hierarchical_domain_discovery/bert_our/src/models/trainer.py", line 142, in train
    for i, batch in enumerate(train_iter):
  File "/Users/vvn/Desktop/hierarchical_domain_discovery/bert_our/src/models/data_loader.py", line 131, in __iter__
    for batch in self.cur_iter:
  File "/Users/vvn/Desktop/hierarchical_domain_discovery/bert_our/src/models/data_loader.py", line 235, in __iter__
    batch = Batch(minibatch, self.device, self.is_test)
  File "/Users/vvn/Desktop/hierarchical_domain_discovery/bert_our/src/models/data_loader.py", line 27, in __init__
    src = torch.tensor(self._pad(pre_src, 0))
  File "/Users/vvn/Desktop/hierarchical_domain_discovery/bert_our/src/models/data_loader.py", line 14, in _pad
    width = max(len(d) for d in data)
ValueError: max() arg is an empty sequence

Could you please help me with this? Thanks a lot!

**Comment by nlpyang** [comment]
Hi, this error means batch_size is too small to contain even one sample.

**Comment by nlpyang** [comment]
here batch_size is the number of tokens in the source documents, since most of them is larger than 300 tokens, you will have this error with batch_size=300

**Comment by tcqiuyu** [comment]
So the batch size here is similar as the max sequence length?  I read the code for a while but still don't get it. I saw in _data_loader.py create_batches()_ function, the batch_size should be relevant to the number of documents instead of number of the tokens. Anywhere to specify that it is related to the **number of tokens** in the source documents?

**Comment by tcqiuyu** [comment]
> here batch_size is the number of tokens in the source documents, since most of them is larger than 300 tokens, you will have this error with batch_size=300

So the batch size here is similar as the max sequence length? I read the code for a while but still don't get it. I saw in data_loader.py create_batches() function, the batch_size should be relevant to the number of documents instead of number of the tokens. Anywhere to specify that it is related to the number of tokens in the source documents? @nlpyang
