### ISSUE TITLE
Bert Fine-tuned problem

### ISSUE THREAD

**Issue by FTUfred** [nlpyang/BertSum#38]
Hi:
![image](https://user-images.githubusercontent.com/49365155/58623978-bb2ceb80-8301-11e9-9368-34064a02b0c2.png)
Are Token Embeddings 、Interval Segment Embeddings and Position Embeddings will be train(Fine-tune)?

Thank you!

**Comment by nlpyang** [comment]
Yes, all of these will be fine-tuned

**Comment by FTUfred** [comment]
Thanks!
In bert
