### ISSUE TITLE
About rouge score

### ISSUE THREAD

**Issue by FTUfred** [nlpyang/BertSum#39]
Hi:

![image](https://user-images.githubusercontent.com/49365155/58681503-3b555e80-839f-11e9-8939-26a50f9d32fe.png)

In the paper, the result is the best result in a checkpoints or the averaged results on the top-3 checkpoints? Becasue in my test the result for bertsum+transformer the best result is 43.23 and the averaged results is 43.1466. 

The **Option 1: download the processed** data use combination_selection or greedy_selection?
Because if use data with **Option 1** will have better rouge result than **Option 2**.

Thanks.

**Comment by nlpyang** [comment]
It is averaged results on the top-3 checkpoints, but with different random seeds, it may change a little.
The results is based on greedy_selection

**Comment by nlpyang** [comment]
Also, you could change the -save_checkpoint_steps setting to get more frequently saved checkpoints, because the difference betwee the top-3 results should be very minor.
