### ISSUE TITLE
Doubt about processed data

### ISSUE THREAD

**Issue by Shashi456** [nlpyang/BertSum#41]
Sorry for opening an issue on this, the doubt is sort of trivial. 
What oracle mode was used for the processed data, combination or greedy?

**Comment by nlpyang** [comment]
greedy

**Comment by Shashi456** [comment]
@nlpyang is the preprocessing format to simpler lines step necessary for preprocessing to bert format and could you tell me what does the map path mean?

**Comment by Shashi456** [comment]
I'm sorry to ask so many questions, and thanks a lot for being patient about it. but how would i change the script if i had a custom dataset, and i just wanted to process the training part for now? as i see things, currently, the entire dataset is passed and you are somehow distributing it in valid test and train.

**Comment by nlpyang** [comment]
If you have a custom dataseg, just format it following the sample file in json_data directory, and run format_to_bert

**Comment by Shashi456** [comment]
@nlpyang I've already processed it to tokenized state

**Comment by nlpyang** [comment]
Ok, so format it the the json file as I defined in the sample file and run format_to_bert.

**Comment by Shashi456** [comment]
@nlpyang so would running this function directly might just do the job right?
```
def _format_to_lines(params):
    f, args = params
    print(f)
    source, tgt = load_json(f, args.lower)
    return {'src': source, 'tgt': tgt} 
```

**Comment by Shashi456** [comment]
since this takes in a tokenized json and returns a normal lined json?

**Comment by nlpyang** [comment]
yes
