### ISSUE TITLE
About preprocessing for CNN/DailyMail

### ISSUE THREAD

**Issue by FTUfred** [nlpyang/BertSum#42]
Hi, 
In your paper or the data **Option 1**  . Did you remove the sentence that shorter than **args.min_nsents**  5(default) for lead3 or any mode in CNN/DailyMail?

Thank you very much.

**Comment by nlpyang** [comment]
min_nsents=3 means we remove documents which has less than 3 sentences.

**Comment by FTUfred** [comment]
Sorry. we have another question. 
What is min_src_ntokens means?

Thanks you
