### ISSUE TITLE
about preprocessing step

### ISSUE THREAD

**Issue by rush86999** [nlpyang/BertSum#43]
can you explain what labels plays a role in bert tokenizer.

especially this code:

`labels = labels[:len(cls_ids)]`

i don't understand what the above code does and how do labels play a part in tokenization for bert?

**Comment by nlpyang** [comment]
i don't know what you mean. this label is the classification label, indicating which sentences should be extracted.

**Comment by rush86999** [comment]
sorry I may be a newbie at this. if I was following the code correctly cls_ids is the id of the 'start token' in bert '[cls]? So why would the length of cls_ids be used to filter the labels under preprocessing? if labels are for classification, all the one-hot vectors of labels should be specific for each label. Is there a specific place I should look at to find the classification labels for these one-hot vectors to better understand the code preprocessing?

I may be misinterpreting the code I have been reading but I seem stumped on how labels are being generated. what does cls_ids represent?

**Comment by nlpyang** [comment]
I am still not sure I understand what you mean here. We are using multiple cls symbols to obtain sentence vectors. The number of labels should be the same as the number of the cls_ids (both equal to the number of sentences of a document).

**Comment by rush86999** [comment]
oh okay, that makes sense now. That is where I was getting confused. they should equal the same so that is what I was trying to understand. Thanks for your patience.
