### ISSUE TITLE
question about candidate

### ISSUE THREAD

**Issue by rush86999** [nlpyang/BertSum#46]
Hello,

 about the trigram blocking. Is the candidate c (as per your paper), a group of 3-grams randomly selected for each source sentence? 

is this the code for the candidate?
```
for i, idx in enumerate(selected_ids):
                            _pred = []
                            if(len(batch.src_str[i])==0):
                                continue
                            for j in selected_ids[i][:len(batch.src_str[i])]:
                                if(j>=len( batch.src_str[i])):
                                    continue
                                candidate = batch.src_str[i][j].strip()
                                if(self.args.block_trigram):
                                    if(not _block_tri(candidate,_pred)):
                                        _pred.append(candidate)
                                else:
                                    _pred.append(candidate)

                                if ((not cal_oracle) and (not self.args.recall_eval) and len(_pred) == 3):
                                    break
```
I m trying to understand this code. It seems 'j' here in the for loop is a character or is it a word? I was trying to match this with preprocessing step and trigram blocking.
```
def _block_tri(c, p):
```

If you can help me understand this code a bit it would be great. 

is this code saying take the character of each source string and find repeating trigrams? is the '_pred' appending each word or character here?

**Comment by nlpyang** [comment]
candidate is a sentence, _pred is the list of summary sentences we will extract.

I think this can be easily understood by actually running and debugging the code.
