### ISSUE TITLE
how long does it take with 3 gpus?

### ISSUE THREAD

**Issue by rush86999** [nlpyang/BertSum#47]
Hello,

 I was wondering how long will take to train the model with 3 gpus? I m trying to calculate the cost and whether it is affordable for me to use an aws p3.16xlarge to train the model.

**Comment by rush86999** [comment]
I wanted to add 1 other question to this as well. I m not finding any code for adding positional embeddings to the preprocessing step. I am assuming the bert model itself takes care of the positional embeddings? If not if you don't mind pointing to the location of the code where positional embeddings are added.

**Comment by nlpyang** [comment]
It takes about 12 hours. Positional emb is not added in preprocessing, but during encoding with BERT.
