### ISSUE TITLE
about positional encoding

### ISSUE THREAD

**Issue by rush86999** [nlpyang/BertSum#48]
under model_builder,

bert is initialized and vectors from bert are fed into the encoder. The encoder itself has positional embedding of vectors (under encoder.py). There are no positional embedding prior to this. Am I to assume the Bert model adds positional embedding to each sentence and we are not required before vectorization to bert?

**Comment by nlpyang** [comment]
please see huggingface BERT https://github.com/huggingface/pytorch-pretrained-BERT for details on BERT
