### ISSUE TITLE
saved checkpoints

### ISSUE THREAD

**Issue by OmerET8** [nlpyang/BertSum#5]
Are you planning to publish your saved checkpoints for the models ? (particularly BERTSUM+Transformer)

Thanks in advance :)

**Comment by nlpyang** [comment]
Sorry for removing the pre-trained model. We are formalizing the pre-print as a paper, the pre-trained model will be released after that.

**Comment by blazejdolicki** [comment]
Any news about releasing the pre-trained model? I think with my rented GPU it would take around 30 hours, so avoiding training would be really helpful ;)

**Comment by nlpyang** [comment]
Please email the author for a pre-trained model.
