### ISSUE TITLE
Use of <q> in gold / pred

### ISSUE THREAD

**Issue by Colanim** [nlpyang/BertSum#54]
I'm trying to understand why you use the token `<q>` when writing gold and prediction (then fed to pyrouge).

Isn't it ok to just put space between summaries ?

I would be very grateful if you could explain this to me.

---

_Note :_

I tried removing it (from prediction and gold summary). The ROUGE-1 and ROUGE-2 score were not impacted, however ROUGE-L score dropped, like 10 points.

**Comment by nlpyang** [comment]
<q> indicates the boundaries between sentences. And pyrouge will use this symbol to segment the generated summary. This will affect the evaluation of Rouge-L since is based on Longest Common Subsequence. If you only want the generated summary, it is OK to replace it with a space.
