### ISSUE TITLE
other types of summarization layer?

### ISSUE THREAD

**Issue by jihun-hong** [nlpyang/BertSum#55]
Hi, thanks for releasing the amazing code on BertSum.
I enjoyed reading your paper on fine-tuning BERT for extractive summarization.

As for the summarization layer, is there a reason that you tried only classifier, inter-sentence transformer, and LSTM? Have you tried using other neural networks as summarization layer, such as a deep neural network?

Thanks! :)

**Comment by nlpyang** [comment]
Not sure what you mean by deep neural network. I think LSTM or Transformer are already deep NNs.

**Comment by jihun-hong** [comment]
I meant a simple feedforward neural network with, for example, six layers.

**Comment by nlpyang** [comment]
I have not tried that. But I don't think it makes a lot of sense for just increasing the depth of the FF network.

**Comment by jihun-hong** [comment]
okay thanks.
