### ISSUE TITLE
Model downloading speed is too slow and failing.

### ISSUE THREAD

**Issue by keyum** [nlpyang/BertSum#56]
https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz not found in cache downloading
0%|▏                                                                                                                  | 555008/407873900 [00:29<33:48:58, 3345.85B/s]
then it stops after 1% or 2%

**Comment by nlpyang** [comment]
Not a problem related to bertsum. Maybe you want to check https://github.com/huggingface/pytorch-pretrained-BERT or your internet for solutions.
