### ISSUE TITLE
Extractive gold label creation process

### ISSUE THREAD

**Issue by Colanim** [nlpyang/BertSum#57]
In the current code, extractive gold label are created by scoring each sentence of the document with the **whole** summary using ROUGE metric and taking the top 3 sentences.

---

However, in other repository (such as [fast_abs_rl](https://github.com/ChenRocks/fast_abs_rl), for abstrative summarization), they created the extractive gold label differently : 

for each sentence of the summary, get the corresponding sentence in the document (regarding ROUGE score).

So they match sentence by sentence between summary and document.

---

**Why this way and not another (like [fast_abs_rl](https://github.com/ChenRocks/fast_abs_rl)) ?**
Is it boosting the ROUGE score ?

**Comment by nlpyang** [comment]
I think this can be answered by calculating the oracle scores. I would prefer our way of doing this. Since for some instances, not all summary sentences can be matched to the document.

**Comment by Colanim** [comment]
Thanks for your answer ! 
Indeed I didn't even think of comparing the oracle baseline ^^

Here is the results :

| Oracle matching  | ROUGE-1 | ROUGE-2 | ROUGE-3 |
|:----------------:|:-------:|:-------:|:-------:|
|     BERT-SUM     |  53.23  |  32.57  |  49.04  |
|    fast-abs-rl   |  47.79  |  28.56  |  44.19  |
