### ISSUE TITLE
token len more than 512

### ISSUE THREAD

**Issue by DavidBeTea** [nlpyang/BertSum#59]
I saw your code, you just select top 510 token from document. 
how about others？
我看CNN的token len分布分位数，512大约是0.25左右。所以你只是用了大约1/4的数据。这样不会有问题吗？

**Comment by nlpyang** [comment]
Not sure what you mean by 25% of the data. The average length of CNNDM articlea is 760. Also, most reference summaries lie in the first 400 tokens. So this will not be a problem for this dataset.

We do have some methods for extending this length limitation. Please wait for our formal paper.

**Comment by DavidBeTea** [comment]
If the average length of CNNDM articles is 760, but your limit is 512, So, you lost more than half informations. But I don't know the summaries lie in the first 400, maybe it's works.

**Comment by nlpyang** [comment]
It is not maybe it works. The experimental results already prove this works.

**Comment by nlpyang** [comment]
And I can't see why this is more than half information lost.

**Comment by DavidBeTea** [comment]
sorry, not half, my mistake. tks for your explanation.

**Comment by bm2515** [comment]
@nlpyang should the number 510 be subject to change if a different dataset is being used?
