### ISSUE TITLE
What to put for 'urls' when preprocessing new data with format_to_lines 

### ISSUE THREAD

**Issue by Santosh-Gupta** [nlpyang/BertSum#62]
For preprocessing in format_to_lines mode, it asks for a MAP_PATH which is the directory containing the urls files (../urls)

A sample text of the urls files in here

https://raw.githubusercontent.com/nlpyang/BertSum/master/urls/mapping_test.txt

However, I am using new data which doesn't have a urls file.

**Comment by nlpyang** [comment]
I would suggest to skip format to lines and run format to bert

**Comment by Santosh-Gupta** [comment]
Thanks! I saw that the urls are only involved with assigning data to train/val/test, so I made a fork to replace that part of the function with random assignments. 

https://github.com/Santosh-Gupta/BertSum/blob/master/src/prepro/data_builder.py
