### ISSUE TITLE
Error when running testing 'FileNotFoundError: [Errno 2] No such file or directory: '/root/.pyrouge/settings.ini''

### ISSUE THREAD

**Issue by Santosh-Gupta** [nlpyang/BertSum#63]
I get this error when i am running testing

> Traceback (most recent call last):
>   File "train.py", line 353, in <module>
>     test(args, device_id, cp, step)
>   File "train.py", line 216, in test
>     trainer.test(test_iter,step)
>   File "/content/BertSum/src/models/trainer.py", line 297, in test
>     rouges = test_rouge(self.args.temp_dir, can_path, gold_path)
>   File "/content/BertSum/src/others/utils.py", line 79, in test_rouge
>     r = pyrouge.Rouge155(temp_dir=temp_dir)
>   File "/content/BertSum/src/others/pyrouge.py", line 123, in __init__
>     self.__set_rouge_dir(rouge_dir)
>   File "/content/BertSum/src/others/pyrouge.py", line 439, in __set_rouge_dir
>     self._home_dir = self.__get_rouge_home_dir_from_settings()
>   File "/content/BertSum/src/others/pyrouge.py", line 453, in __get_rouge_home_dir_from_settings
>     with open(self._settings_file) as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/root/.pyrouge/settings.ini'

Here is a direct public link to the notebook I am working on 

https://colab.research.google.com/drive/1vKYu-RPR5FJ1ZukTC7JDcfDYK6bm45eq

**Comment by Santosh-Gupta** [comment]
I see it's been addressed here
https://github.com/nlpyang/BertSum/issues/35

**Comment by DarlineFiedler** [comment]
I have a Question. How do you solve that Problem? I'm using google Cloab and ich don't know how i fix that issue.
