### ISSUE TITLE
Question about test_rouge function

### ISSUE THREAD

**Issue by TianyuZhuuu** [nlpyang/BertSum#64]
Hi Yang Liu,

Thanks for sharing the code! However, I'm confused about the _test_rouge_ function under _others/utils.py_. 

https://github.com/nlpyang/BertSum/blob/8a6e2924725697a574d8c500906c9dd6f9151778/src/others/utils.py#L30-L44

In my opinion, _reference_ should be given highlights and _candidates_ should be model outputs.   It seems you swapped them. Could you double check with that?

**Comment by nlpyang** [comment]
Hi,

I think this is correct. Candidates are written in the 'candidate' directory, and references are written in the 'reference' directory. Maybe you mean that the name 'model_dir' is confusing? In Rouge, model_dir means directory for gold-standard summaries and 'system_dir' means directory for candidate summaries. (https://kavita-ganesan.com/rouge-howto/)

**Comment by TianyuZhuuu** [comment]
Got it. I also found there's an instruction in pyrouge's [documentation](https://github.com/bheinzerling/pyrouge).  I overlooked it before. Thanks for your reply!

![image](https://user-images.githubusercontent.com/40353467/62111918-f98c5a00-b2f4-11e9-8fcd-1076747e20ba.png)
