### ISSUE TITLE
Is it possible to set `load_pretrained_bert=False` in `model = Summarizer(args, device, load_pretrained_bert=True)` if we use a checkpoint?

### ISSUE THREAD

**Issue by Santosh-Gupta** [nlpyang/BertSum#66]
https://github.com/nlpyang/BertSum/blob/master/src/train.py#L256

My impression that it's sort of a waste if we download and load the pretrained checkpoint only to replace them with your own checkpoint. Or, there might be a deeper reason for this.

**Comment by nlpyang** [comment]
not sure what you meant by this. please propose an alternative if you thought of one.
