### ISSUE TITLE
BERTSUM for German dataset

### ISSUE THREAD

**Issue by najmia** [nlpyang/BertSum#75]
Is there a way to use the existing BERTSUM model or the pertained BERT (German) for this use case? I have a dataset of German articles and I would like to generate one sentence summaries for the same. Is there a way to leverage your implementation for English articles to German ones?

**Comment by najmia** [comment]
There is a possibility of using the German BERT model developed by Deepset.ai team, available on pytorch-transformers

**Comment by zakhan4** [comment]
Hi,

I have a similar problem. Can you please tell me if we have to do the pre-training for the BERTSUM using the pretrained German BERT, before fine-tuning it on a new dataset according to the research paper?

Or only fine-tuning will also suffice? 
Thanks!

**Comment by DarlineFiedler** [comment]
I also need a German version. Do you have a solution yet?

**Comment by zakhan4** [comment]
@DarlineFiedler as far as my knowledge. You don't need to do pretraining again, but can fine-tune Bert pre-trained on German dataset by Deepset.ai team. Here is the link: https://huggingface.co/bert-base-german-cased
