### ISSUE TITLE
A question about preprocessing

### ISSUE THREAD

**Issue by futianfan** [nlpyang/BertSum#8]
Hi,

I have some problems in preprocessing. 

I download the data cnn_stories_tokenized and dm_stories_tokenized, however, it's all *.story. In your preprocess.py, it requires *.json as input, can you provide the code that transform *.story to *.json? I meet some problem in reading the sample json with you load_json function in data_builder.py. Appreciated!

**Comment by nlpyang** [comment]
please see sample json file for reference. You can generate them by using json as outputFormat in corenlp.

**Comment by weiyengs** [comment]
Is the generation of JSON file performed by:
"python preprocess.py -mode format_to_lines -raw_path RAW_PATH -save_path JSON_PATH -map_path MAP_PATH -lower " ?

Seems that this command is not generating as well.

**Comment by futianfan** [comment]
Thanks for reply. I will try it.

**Comment by nlpyang** [comment]
Hi,
Please check the updated instruction for preprocessing the data.
It should work fine now.

**Comment by futianfan** [comment]
It works now, appreciate!

**Comment by AyeshaSarwar** [comment]
python preprocess.py -mode format_to_lines -raw_path RAW_PATH -save_path JSON_PATH -map_path MAP_PATH -lower

This command returns me nothing, and no output files are generated as well. What error could it be?
