### ISSUE TITLE
"Step 4. Format to Simpler Json Files" not  working

### ISSUE THREAD

**Issue by RafaelWO** [nlpyang/BertSum#82]
Hi, I tried to run the code with the same data, but the when executing the suggested line in Step 4 `python preprocess.py -mode format_to_lines -raw_path RAW_PATH -save_path JSON_PATH -map_path MAP_PATH -lower` nothing happend. Somehow the json files are not created. Can someone help me out? Or do I have to recreate the required format on my own?

**Comment by RafaelWO** [comment]
Somehow I was doing something wrong, code is working fine, sorry!

**Comment by AyeshaSarwar** [comment]
Can you please let me know how you solved it because it is giving me the same response. Possible errors?
Thanks in advance

**Comment by progsi** [comment]
same for me, thanks in advance!

**Comment by ntnshrav** [comment]
I  am also facing the same issue. Please let me know how it was solved for you.

**Comment by RafaelWO** [comment]
Sorry, I don't remember how I "solved" this for me. Maybe the path needs to be specified in a different way? Do all needed directories exist?

You can always debug the code and find the issue (I did this as well to understand what exactly happens in each step).
