### ISSUE TITLE
No such file or directory: '../logs/cnndm.log'

### ISSUE THREAD

**Issue by siddas27** [nlpyang/BertSum#88]
`python preprocess.py -mode tokenize -raw_path ../raw_data -save_path ../json_datas` got this error:

```
Traceback (most recent call last):
  File "preprocess.py", line 62, in <module>
    init_logger(args.log_file)
  File "/home/sid/project/BertSum-master/src/others/logging.py", line 19, in init_logger
    file_handler = logging.FileHandler(log_file)
  File "/opt/anaconda/envs/nlp/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/anaconda/envs/nlp/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '../logs/cnndm.log'
```

**Comment by RafaelWO** [comment]
Check if the relative paths (`../`) are valid for working directory (for your call your working dir should be `path/to/bertsum/src`). Otherwise, creating the folder + file could help.

**Comment by siddas27** [comment]
My working directory is inside`src` only. But couldn't find the `cnndm.log` file anywhere. Can you tell me from where I can get it or create it?

**Comment by RafaelWO** [comment]
Just create a file named `cmmd.log` via your file explorer (or CLI or whatever you want).

**Comment by siddas27** [comment]
Thanks, I thought I have to download it from somewhere

**Comment by RafaelWO** [comment]
So I guess you can close this issue? :heavy_check_mark:
