### ISSUE TITLE
KeyError: 'paper_id'

### ISSUE THREAD

**Issue by sayeedk06** [nlpyang/BertSum#94]
Whats the issue here? After running the python train.py command as in read me. This error shows up

> `[2020-04-21 12:36:18,824 INFO] * number of parameters: 109483009
> [2020-04-21 12:36:18,824 INFO] Start training...
> [2020-04-21 12:36:18,827 INFO] Loading train dataset from ../bert_data/cnndm.train.123.bert.pt
> [2020-04-21 12:36:18,934 INFO] Loaded train dataset from ../bert_data/cnndm.train.123.bert.pt, number of examples: 2001
> Traceback (most recent call last):
>   File "train.py", line 395, in <module>
>     train(args, device_id)
>   File "train.py", line 323, in train
>     trainer.train(train_iter_fct, args.train_steps)
>   File "/content/drive/My Drive/i_have_no_idea/BertSum/src/models/trainer.py", line 142, in train
>     for i, batch in enumerate(train_iter):
>   File "/content/drive/My Drive/i_have_no_idea/BertSum/src/models/data_loader.py", line 175, in __iter__
>     for batch in self.cur_iter:
>   File "/content/drive/My Drive/i_have_no_idea/BertSum/src/models/data_loader.py", line 274, in __iter__
>     for idx, minibatch in enumerate(self.batches):
>   File "/content/drive/My Drive/i_have_no_idea/BertSum/src/models/data_loader.py", line 260, in create_batches
>     for buffer in self.batch_buffer(data, self.batch_size * 50):
>   File "/content/drive/My Drive/i_have_no_idea/BertSum/src/models/data_loader.py", line 243, in batch_buffer
>     ex = self.preprocess(ex, self.is_test)
>   File "/content/drive/My Drive/i_have_no_idea/BertSum/src/models/data_loader.py", line 231, in preprocess
>     paper_id = ex['paper_id']
> KeyError: 'paper_id'`

**Comment by namhkoh** [comment]
How did you solve it?
