### ISSUE TITLE
"Step 4. Format to Simpler Json Files" no output

### ISSUE THREAD

**Issue by progsi** [nlpyang/BertSum#96]
Firstly, thank you for the code and instructions!

When running preprocessing step to "format_to_lines" I do not get any output. It runs for 3-10 seconds or so.

Thanks in advance for your help!

**Comment by lee2015new** [comment]
> Firstly, thank you for the code and instructions!
> 
> When running preprocessing step to "format_to_lines" I do not get any output. It runs for 3-10 seconds or so.
> 
> Thanks in advance for your help!

Do you use the CNN/Dailymail data or not? If you use yourself data you need ignore the MAP_PATH.

**Comment by progsi** [comment]
thanks for the quick reply! I am using the CNN/Dailymail dataset

**Comment by progsi** [comment]
seems like I found the Issue. The format_to_lines function in the data_builder had different interpretation of path separators than my OS. ("/" vs " \ ")

**Comment by DarlineFiedler** [comment]
What exactly have you changed? I have the same problem and I can't solve it. Even if I change the path separators.

**Comment by yuxuan512** [comment]
I have the same problem. Have you solved this? I still have nothing output.
